[workspace]
resolver = "2"
members = [
    "crates/apk-patch-meta",
    "crates/apk-patch-project",
    "crates/apk-patch-dex",
    "crates/apk-patch-framework",
    "crates/apk-patch-resources",
    "crates/apk-patch-sign",
    "crates/apk-patch-core",
    "crates/apk-patch-cli",
]

[workspace.package]
edition = "2021"
license = "Apache-2.0"
version = "0.1.0"

[workspace.dependencies]
apkparser = { path = "../apk-parser/apkparser-rs" }
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
simple_logger = "4.3"
thiserror = "1.0"
walkdir = "2.5"
